default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: "(.pre-commit-config.yaml|Pipfile.lock)"