# Good reference list of pre-commit repos:
# https://gdevops.gitlab.io/tuto_git/tools/pre-commit/repos_hooks/repos_hooks.html#alessandrojcm-commitlint-pre-commit-hook
default_stages: [pre-commit]
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-ll"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff  # linter
        args: [ --line-length=120 , --fix, --select, I]
      - id: ruff-format  # formatter
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true
        args: [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--disable=line-too-long,invalid-name,broad-exception-raised,global-statement,multiple-statements,duplicate-code",
          "--disable=too-many-locals,too-many-nested-blocks,too-many-branches,too-many-arguments,too-many-positional-arguments,too-many-statements,too-many-return-statements",
          "--disable=missing-module-docstring,missing-class-docstring,missing-function-docstring,import-error,fixme,pointless-string-statement"
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --show-error-codes, --ignore-missing-imports]
        language: python
        types: [python]
        additional_dependencies: [pydantic]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1
    hooks:
      - id: hadolint
        args: [--ignore, DL3048]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    - id: pyupgrade
      args: [--py39-plus]
