[project]
version = "0.1.0"
name = "advent-of-code"
description = "Project to participate in Advent of Code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "heapdict>=1.0.1",
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "pylint>=3.3.9",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.0",
]

[tool.ruff]
lint.select = ["ALL"]
lint.fixable = ["ALL"]
lint.ignore = [
    "D100",
    "D203",
    "D213",
    "COM812",   # Disable per ruffs suggestion
    "N815",
    "TRY003",
]

line-length = 120
indent-width = 4
show-fixes = true
src = ["."]
target-version = "py312"

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.per-file-ignore]
# Ignore all pydocstyle linting issues for tests
"__init__.py" = ["DOC", "D"]
# PLR2004 enables magic string/int comparisons in tests
"**/tests/**test_*.py" = ["DOC", "D", "S101", "PLR2004"]
# N999 is dubious...
"**/features/steps/**.py" = ["DOC", "D", "S101", "PLR2004", "N999"]

[tool.ruff.lint.flake8-tidy-imports]
# disallow all relative imports
ban-relative-imports = "all"

[tool.ruff.lint.pylint]
allow-magic-value-types = []
max-nested-blocks = 2
max-args = 10

[tool.coverage.report]
fail_under = 90
show_missing = true
skip_covered = true
exclude_lines = ["pragma: no cover"]

[tool.coverage.run]
branch = true
source = ["."]
omit = ["env.py"]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
show_error_code_links = true
hide_error_codes = false
pretty = true
python_version = "3.12"
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = "*"
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
warn_unused_ignores = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true